name: Adler Santos
description: Data Scientist and Software Engineer
meta_description: "Adler Santos, Data Scientist and Software Engineer"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 10
baseurl: /
domain_name: 'http://adlersantos.com'
google_analytics: 'UA-44190159-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://adlersantos.com'
author:         'Adler Santos'
authorTwitter:  'adlersantos'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
